inotify: fix root cause of a flaky test
Finally got to the bottom of this test failure:

```
FAIL test_since.TestSince.test_sinceIssue2 [local, bser] (0.006s)
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/unittest2/case.py", line 340, in run
    testMethod()
  File "/data/users/wez/watchman/tests/integration/test_since.py", line 67, in test_sinceIssue2
    self.assertFileList(root, cursor='n:foo', files=expected)
  File "/data/users/wez/watchman/tests/integration/WatchmanTestCase.py", line 251, in assertFileList
    self.assertFileListsEqual(self.last_file_list, expected_files, message)
  File "/data/users/wez/watchman/tests/integration/WatchmanTestCase.py", line 231, in assertFileListsEqual
    self.assertEqual(list1, list2, message)
  File "/usr/lib/python2.6/site-packages/unittest2/case.py", line 521, in assertEqual
    assertion_func(first, second, msg=msg)
  File "/usr/lib/python2.6/site-packages/unittest2/case.py", line 752, in assertListEqual
    self.assertSequenceEqual(list1, list2, msg, seq_type=list)
  File "/usr/lib/python2.6/site-packages/unittest2/case.py", line 734, in assertSequenceEqual
    self.fail(msg)
  File "/usr/lib/python2.6/site-packages/unittest2/case.py", line 415, in fail
    raise self.failureException(msg)
AssertionError: Lists differ: ['foo', 'foo/111', 'foo/bar', ... != ['foo/bar', 'foo/bar/222']

First differing element 0:
foo
foo/bar

First list contains 2 additional elements.
First extra element 2:
foo/bar

- ['foo', 'foo/111', 'foo/bar', 'foo/bar/222']
+ ['foo/bar', 'foo/bar/222']
```

The issue is that, under concurrency, linux can be pretty tardy about
delivering the IN_CLOSE_WRITE notification for a file handle.

From the logs in this test we see the IN_CLOSE_WRITE for `foo/111` get
delivered after the notifications about the creation of the `222` file and
after we've started processing cookie notifications.  Since these notifications
are coming from inotify we will unconditionally mark the file node as modified
and that brings it forwards into the result set for the end of this test case.

This diff removes `IN_CLOSE_WRITE` from the notification mask.

Test Plan: make integration passes more consistently.  Also ran the mercurial test suite with fsmonitor enabled:

```
WATCHMAN_CONFIG_FILE=/dev/null PATH=/tmp/wez-wat-test/bin:$PATH ./run-tests.py --extra-config-opt=extensions.fsmonitor= -j 20
```

and saw no unexpected failures (only things relating to largefiles, eol, subrepos and so on)