fix build on Linux
```
listener.c: In function ‘w_should_log_to_clients’:
listener.c:533:3: error: ISO C90 forbids mixed declarations and code
[-Werror=declaration-after-statement]
cc1: all warnings being treated as errors
```

We have configure turn these into errors, but clang on osx apparently
ignores these flags, so this slipped through :-/