fix windows build break in wildmatch
Summary:
Windows CI was breaking with: ```Z:\shipit\watchman\watchman\thirdparty\wildmatch\wildmatch.c(90): error C2065: 'fallthrough': undeclared identifier```

Looks like this was introduced in D56223962 which broke it as the windows compiler doesn't support the attribute

Reviewed By: xavierd

Differential Revision: D56567731

fbshipit-source-id: 315ff8165f31e6055ccd39ee63081bc63b564689