fixup windows compilation
Summary:
We don't have `stat()`, but do have `lstat()` available.

```
scm\Mercurial.cpp(42): error C2440: '<function-style-cast>': cannot convert from 'initializer list' to 'stat'
scm\Mercurial.cpp(42): note: No constructor could take the source type, or constructor overload resolution was ambiguous
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\BIN\amd64\cl.EXE"' : return code '0x2'
```

Differential Revision: D4650244

fbshipit-source-id: 7c7b29ccd994a788d873866d4c150d835d2b7f28