fix windows & mac release failures
Summary:
The Windows and mac watchman releases have been broken since the 8th with
the error:

```
error: failed to select a version for the requirement `sysinfo = "^0.20"`
candidate versions found which didn't match: 0.26.8
```

looks like D41813852 just missed bumping this dependency when we upgraded the
package.

Reviewed By: fanzeyi

Differential Revision: D42004372

fbshipit-source-id: 176db5271b8893c9644091f945489469ae644ef3