watchman/ProcessLock.h: avoid C++20 build failure
Summary:
Move default constructor from private to public, now seemingly required for C++20
This avoids the following errors:

  watchman/ProcessLock.cpp:161:10: error: calling a private constructor of class 'watchman::ProcessLock::Handle'

Differential Revision: D32259017

fbshipit-source-id: 9765180a6b6b61a4ac4a1bfed64c2cb43a15359c