update node client example and docs to use watch-project
Summary:
Shows how you might use relative_path to compensate for the offset
in the query expression and in the subscription event handler.

Need to add an expression term to make it simpler to match under a dir prefix
so that these don't require the use of pcre.

Test Plan:
ran the example locally:

```
$ node ./example.js
Talking to watchman version 3.1.0
failed to subscribe:  { [Error: unknown command invalid-command-never-will-work]
  watchmanResponse:
   { version: '3.1.0',
     error: 'unknown command invalid-command-never-will-work' } }
(re)using project watch at  /Users/wez/fb/watchman , our dir is relative:  node/
subscription mysubscription established
/Users/wez/fb/watchman mysubscription
{ name: 'example.js', size: 5698, exists: true, type: 'f' }
{ name: 'node_modules/json-stream/test/json-stream-test.js',
  size: 1539,
  exists: true,
  type: 'f' }
{ name: 'node_modules/json-stream/test/pipe-test.js',
  size: 749,
  exists: true,
  type: 'f' }
{ name: 'node_modules/json-stream/test/throw-in-readable-test.js',
  size: 305,
  exists: true,
  type: 'f' }
{ name: 'node_modules/json-stream/lib/json-stream.js',
  size: 943,
  exists: true,
  type: 'f' }
{ name: 'node_modules/nextback/test/main.js',
  size: 1224,
  exists: true,
  type: 'f' }
{ name: 'node_modules/nextback/index.js',
  size: 229,
  exists: true,
  type: 'f' }
{ name: 'index.js', size: 5232, exists: true, type: 'f' }
subscription sincesub established
```

Reviewers: amasad, sid0

Reviewed By: sid0

Differential Revision: https://reviews.facebook.net/D36465