watchman_client: specify minimal dependent serde version to 1.0.102
Summary:
When `watchman_client` is used with serde < 1.0.102, it will returns an error:

```
Error: ConnectionDiscovery { watchman_path: "watchman", reason: "error while deserializing BSER: invalid type: byte array, expected path string", stderr: "" }
```

This is because serde only added `Path` serialization support in 1.0.102 and before that `Path` will be serialized as string instead of byte array.

The following code (`test.rs`):

```
//# serde = "=1.0.101"
//# watchman_client = { path = "*" }
//# tokio = "*"

use watchman_client::prelude::*;

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
  let mut client = Connector::new().connect().await?;
  let resolved = client
    .resolve_root(CanonicalPath::canonicalize(".")?)
    .await?;

  // Basic globs -> names
  let files = client.glob(&resolved, &["**/*.rs"]).await?;
  println!("files: {:#?}", files);
  Ok(())
}
```

will produce that error message.

This typically happens when there is an existing `Cargo.lock` that locked serde version to a version prior to 1.0.102. Specifying the minimal version will make Cargo to recalculate the lock file.

Reviewed By: wez

Differential Revision: D19281100

fbshipit-source-id: 8562481f27f8c1641ff2d00d92ee37d3dc51e261