fix oss Windows build
Summary:
Otherwise the build will fail with

```
Traceback (most recent call last):
  File "C:/Users/zeyi/GitHub/watchman/watchman/python/setup.py", line 25, in <module>
    py_dir = os.path.relpath(py_dir)
  File "C:\Python38\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'C:', start on mount 'Z:'
CMake Error at cmake_install.cmake:44 (message):
  pywatchman install failed
```

This is because getdeps tries to build on a different drive on Windows and that breaks the relative path calculation.

Reviewed By: kmancini

Differential Revision: D29998898

fbshipit-source-id: 8d9d809e992e2d35dec1357ecbaa39cf45509adc