Fix python/setup.py outside CMake
Summary:
D15300087 made setup.py work better when invoked from CMake, but broke setup.py when invoked directly:

```
$ /usr/bin/python setup.py install --root instroot
running install
running build
running build_py
error: package directory '[snip]/watchman/python/python/pywatchman' does not exist
```

This happens because setup.py's `py_dir` variable is set to `".../watchman/python/python"`, but that path doesn't exist. `py_dir` is wrong because `src_dir` is wrong; when the `CMAKE_SOURCE_DIR` environment variable is not set, `src_dir` is set to `".../watchman/python"`.

Fix setup.py when run directly by setting `src_dir` to `".../watchman"` instead of `".../watchman/python"`.

Reviewed By: wez

Differential Revision: D15457847

fbshipit-source-id: 0a4b490b6da56033160abbcadb27b7bedce6a3b0