Install pip in Ubuntu buildenv (#1331)
Summary:
getdeps requires pip for `install-system-packages` since D77674102, causing errors in the packaging workflow:
```
 ---
+ pip \
+      install \
+      pex
error running `pip \
+      install \
Traceback (most recent call last):
  File "/__w/watchman/watchman/build/fbcode_builder/getdeps/runcmd.py", line 108, in _run_cmd
    p = subprocess.Popen(
        ^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/subprocess.py", line 1026, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.12/subprocess.py", line 1955, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'pip'
```

Pull Request resolved: https://github.com/facebook/watchman/pull/1331

Reviewed By: genevievehelsel

Differential Revision: D90919043

fbshipit-source-id: 92fc19d7bbfac97ac303176a2c80ebbf1b52c8a6