fixup integration tests on python 2.6
Summary:
Seeing this on travis:

```
FAIL unittest2.loader._FailedTest.test_php (0.000s)
Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/2.6.9/lib/python2.6/site-packages/unittest2/case.py", line 67, in testPartExecutor
    yield
  File "/Users/travis/.pyenv/versions/2.6.9/lib/python2.6/site-packages/unittest2/case.py", line 625, in run
    testMethod()
  File "/Users/travis/.pyenv/versions/2.6.9/lib/python2.6/site-packages/unittest2/loader.py", line 51, in testFailure
    raise self._exception
ImportError: Failed to import test module: test_php
Traceback (most recent call last):
  File "/Users/travis/.pyenv/versions/2.6.9/lib/python2.6/site-packages/unittest2/loader.py", line 456, in _find_test_path
    module = self._get_module_from_name(name)
  File "/Users/travis/.pyenv/versions/2.6.9/lib/python2.6/site-packages/unittest2/loader.py", line 395, in _get_module_from_name
    __import__(name)
  File "/Users/travis/build/facebook/watchman/tests/integration/test_php.py", line 74, in <module>
    class PHPTestCase(unittest.TestCase):
  File "/Users/travis/build/facebook/watchman/tests/integration/test_php.py", line 76, in PHPTestCase
    unittest.skipIf(php_bin is None, 'php not installed')
AttributeError: 'module' object has no attribute 'skipIf'
```

Transplant in the unittest2 import that we use in the other tests that use skipIf.

Reviewed By: sid0

Differential Revision: D4165578

fbshipit-source-id: c106d769d690ae2d79936dfaa3d76166ee78d601