Fix "use of undeclared identifier 'WATCHMAN_CONFIG_FILE'"
Summary:
Configuring Watchman with --enable-conffile=no causes Watchman to fail
to compile:

    cmds/watch.cpp:231:7: error: use of undeclared identifier 'WATCHMAN_CONFIG_FILE'
	  WATCHMAN_CONFIG_FILE,
	  ^
    root/resolve.cpp:220:9: error: use of undeclared identifier 'WATCHMAN_CONFIG_FILE'
            WATCHMAN_CONFIG_FILE,
            ^

Using WATCHMAN_CONFIG_FILE in these places is wrong for two reasons:

* The WATCHMAN_CONFIG_FILE macro may be not defined, hence the
  compilation error with --enable-conffile=no.
* The user can set WATCHMAN_CONFIG_FILE at run-time using the
  WATCHMAN_CONFIG_FILE environment variable.

Fix the compilation error by exposing the config file's path from the
config module.

Reviewed By: wez

Differential Revision: D8431235

fbshipit-source-id: d474ae60eec1c7adff25ef943555e11ef957dab7