Fix casts from values to pointers
The casts produced this error while compiling on my 32-bit Debian
system:

  root.c: In function 'invalidate_watch_descriptors':
  root.c:655:34: error: cast to pointer from integer of different size
    [-Werror=int-to-pointer-cast]
  root.c: In function 'w_root_resolve_dir_by_wd':
  root.c:910:10: error: cast to pointer from integer of different size
    [-Werror=int-to-pointer-cast]

The ht_val_ptr function was used to do the correct casts.