Completely ignore is_pcre when PCRE isn't available
I did not have the PCRE headers so HAVE_PCRE_H was false. That
resulted in this error while compiling:

  rules.c: In function 'parse_watch_params':
  rules.c:207:7: error: variable 'is_pcre' set but not used
    [-Werror=unused-but-set-variable]

The ifdef's now completely remove the is_pcre variable when PCRE isn't
available.